#!/usr/bin/with-contenv bash
#
set -e
set -x

java -version

cd /jmr
java -Dconfig.file=/etc/jitsi/jmr/jmr.conf -Djava.util.logging.config.file=/etc/jitsi/jmr/logging.properties -jar ./jitsi-multitrack-recorder-0.1-SNAPSHOT-jar-with-dependencies.jar org.jitsi.recorder.MainKt
